name: Regression Tests

on:
  # push:
  #   branches: [ main, development ]
  workflow_dispatch:

env:
  UI_BASE_URL: https://practicesoftwaretesting.com
  API_BASE_URL: https://api.practicesoftwaretesting.com

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: npx playwright test --project=chromium --grep @regression

    - name: Upload blob report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: blob-report
        path: blob-report
        retention-days: 7

    - name: Upload allure results
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
        retention-days: 7

  merge-report:
    if: ${{ !cancelled() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci

      - uses: actions/download-artifact@v4
        with:
          path: blob-report
          pattern: blob-report

      - run: npx playwright merge-reports --reporter html ./blob-report/blob-report

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report
          retention-days: 14

      - uses: actions/download-artifact@v4
        with:
          path: allure-results
          pattern: allure-results

      - name: Generate Allure report
        run: npx allure-commandline generate ./allure-results/allure-results --clean -o ./allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 14
